name: enhanced_dnd_dice_roller
description: A comprehensive D&D dice roller with full character sheet integration
version: 2.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  sqflite: ^2.3.0
  path: ^1.8.3
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # If you want to add assets (optional)
  # assets:
  #   - assets/images/
  #   - assets/sounds/
  
  # Example fonts (optional)
  # fonts:
  #   - family: DndFont
  #     fonts:
  #       - asset: fonts/DndFont-Regular.ttf
  #       - asset: fonts/DndFont-Bold.ttf
  #         weight: 700
